export const notifications = [
  {
    id: "notification-1",
    actorId: "user-003",
    type: "follow",
    message: "started following you.",
    actionLabel: "Follow Back",
    unread: true,
    highlighted: true,
  },
  {
    id: "notification-2",
    actorId: "user-004",
    type: "follow",
    message: "started following you.",
    actionLabel: "Follow Back",
    unread: false,
    highlighted: false,
  },
  {
    id: "notification-3",
    actorId: "user-002",
    type: "follow",
    message: "started following you.",
    actionLabel: "Follow Back",
    unread: false,
    highlighted: false,
  },
  {
    id: "notification-4",
    actorId: "user-006",
    type: "comment",
    message: "Replied you in chat.",
    actionLabel: "Reply",
    unread: false,
    highlighted: false,
  },
  {
    id: "notification-5",
    actorId: "user-001",
    type: "like",
    message: "Liked your event post.",
    actionLabel: "View Profile",
    unread: false,
    highlighted: false,
  },
  {
    id: "notification-6",
    actorId: "user-005",
    type: "follow",
    message: "started following you.",
    actionLabel: "Follow Back",
    unread: false,
    highlighted: false,
  },
];
